### ISSUE TITLE
使用internvideo2.5的时候，有的视频会报错。

### ISSUE THREAD

**Issue by Sakura-not-sleep** [OpenGVLab/InternVideo#253]
您好，在使用internvideo2.5的时候，有的视频会出现如下报错：decord._ffi.base.DECORDError: [21:21:05] /github/workspace/src/video/video_reader.cc:486: Error: av_read_frame failed with 1094995529。请问这个报错该如何解决，非常感谢您。

**Comment by yinanhe** [comment]
这个视频在其他的codebase下可以读取吗

**Comment by sakura-001-wjx** [comment]
> 这个视频在其他的codebase下可以读取吗

我刚才在videollama3的online demo上试了下是可以的，我在做一些视频的下游任务，我给Internvideo2.5输入了500多个视频，有61个视频都出现了上面的报错，应该不是视频损坏的原因，我重新往服务器上传了下还是不行。我中间换了一下提示词变成62个报错了，我试了很多次，基本都是61个报错，只有那次是62个。

**Comment by sakura-001-wjx** [comment]
> 这个视频在其他的codebase下可以读取吗

我刚才在InternVL2.5上面也试了下，那些视频还是会出错，不够这次出错是60个，基本还是上面那些，这是怎么回事欸。

**Comment by leexinhao** [comment]
什么格式的视频呢，如果不是mp4格式的推荐用这个函数：https://huggingface.co/OpenGVLab/VideoChat-Flash-Qwen2-7B_res448/blob/816c62936b6d314d1c8d04cec34fcc17338540f9/modeling_videochat_flash.py#L635

**Comment by Sakura-not-sleep** [comment]
> 什么格式的视频呢，如果不是mp4格式的推荐用这个函数：https://huggingface.co/OpenGVLab/VideoChat-Flash-Qwen2-7B_res448/blob/816c62936b6d314d1c8d04cec34fcc17338540f9/modeling_videochat_flash.py#L635

好的，已经解决了，非常感谢！
